#ifndef CONFIG_H
#define CONFIG_H

#define SCALE_FACTOR_X 2
#define SCALE_FACTOR_Y 1

#define CELL_WIDTH  (5 * SCALE_FACTOR_X)
#define CELL_HEIGHT (5 * SCALE_FACTOR_Y)

#define BORDER_SIZE_Y (5 * SCALE_FACTOR_Y)
#define BORDER_SIZE_X (5 * SCALE_FACTOR_X)

#define FIELD_WIDTH  (10 * CELL_WIDTH)
#define FIELD_HEIGHT (10 * CELL_HEIGHT)

#define SCREEN_WIDTH  (FIELD_WIDTH + BORDER_SIZE_X * 2)
#define SCREEN_HEIGHT (FIELD_HEIGHT + BORDER_SIZE_Y * 2)

// #define SNAKE_UP    CURSOR_UP
// #define SNAKE_DOWN  CURSOR_DOWN
// #define SNAKE_LEFT  CURSOR_LEFT
// #define SNAKE_RIGHT CURSOR_RIGHT
// #define SNAKE_STAY  CURSOR_STAY

// #define SNAKE_DEFAULT_COORDS (Coords){.x = 0, .y = 1}

// #define BORDER_SIZE 1

// #define SCORE_COUNER_HEIGHT 1

// #define SNAKE_GRID_HEIGHT 20
// #define SNAKE_GRID_WIDTH  20

// #define SNAKE_GRID_CELL_SIZE 2

// #define SNAKE_AREA_OFFSET_Y SCORE_COUNER_HEIGHT + BORDER_SIZE
// #define SNAKE_AREA_HEIGHT (SNAKE_GRID_HEIGHT * SNAKE_GRID_CELL_SIZE)
// #define SNAKE_AREA_WIDTH  (SNAKE_GRID_WIDTH  * (SNAKE_GRID_CELL_SIZE * 2))

// #define SNAKE_MAX_SIZE SNAKE_GRID_HEIGHT * SNAKE_GRID_WIDTH

// #define SCREEN_HEIGHT SNAKE_AREA_HEIGHT + SNAKE_AREA_OFFSET_Y + (BORDER_SIZE * 2)
// #define SCREEN_WIDTH  SNAKE_AREA_WIDTH  + (BORDER_SIZE * 2)

#endif
